[package]
name = "keyboard"
version = "0.1.0"
edition = "2018"
description = "Keyboard input handler"

[dependencies]
printk = { path = "../../../kernel/printk/" }

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]
