[package]
name = "init"
version = "0.1.0"
edition = "2018"
description = "Main kernel initialization"

[dependencies]
cfg-if = "1.0.0"
gpu = { path = "../drivers/gpu/" }
kinfo = { path = "../kernel/kinfo/" }
konfig = { path = "../kernel/konfig/", features = ["default_config"] }
lazy_static = "1.4.0"
modules = { path = "../kernel/modules/" }
pc_keyboard = { path = "../drivers/input/keyboard/pc_keyboard/" }
novuskinc = { path = "../include/novusk/" }
printk = { path = "../kernel/printk/" }
spin = { version = "0.9.2", features = ["spin_mutex"] }
