[package]
name = "init"
version = "0.1.0"
edition = "2018"
description = "Main kernel initialization"


[dependencies]
cfg-if = "1.0.0"
gpu = { path = "../drivers/gpu/" }
kinfo = { path = "../kernel/kinfo/" }
lazy_static = "1.4.0"
printk = { path = "../kernel/printk/" }
spin = { version = "0.9.2", features = ["spin_mutex"] }