[package]
name = "novusk"
version = "3.0.0-beta-arch-v1.1"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
path = "src/main.rs"
edition = "2018"

[lib]
name = "novusk"
path = "src/lib.rs"
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/aarch64/",
    "arch/arm/",
    "arch/x86/",
    # Drivers
    "drivers/firmware/arm/nrfd/",
    "drivers/firmware/rpi/",
    "drivers/gpu/",
    "drivers/usb/",
    "drivers/nkuefi/",
    # GPUs
    # Kernel
    "kernel/kinfo/",
    "kernel/modules/",
    "kernel/printk/",
    # Libraries
    "lib/libcolor/",
    # MM
    "mm/io/",
    # Sound
    "sound/x86_64-sound/",
    # Kernel Modules
    "kernel/modules/ex1/",
    # Tools
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = { version = "0.9.12" }
x86 = { path = "arch/x86/" }

[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path = "arch/x86/" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = { path = "arch/aarch64/" }

[target.'cfg(target_arch = "arm")'.dependencies]
arm = { path = "arch/arm/" }

[dependencies]
kinfo = { path = "kernel/kinfo/" }
libcolor = { path = "lib/libcolor/" }
printk = { path = "kernel/printk/" }
register = { version = "1.0.2", optional = true }

[features]
default = []
