[package]
name = "novusk"
version = "3.0.0-beta-kernel-v2"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
path = "src/main.rs"
edition = "2018"

[lib]
name = "novusk"
path = "src/lib.rs"
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/aarch64/",
    "arch/arm/",
    "arch/riscv/",
    "arch/x86_64/",
    "arch/xtensa/",
    # Drivers
    "drivers/blue/",
    "drivers/firmware/arm/nrfd/",
    "drivers/gpu/",
    "drivers/input/keyboard/",
    "drivers/input/keyboard/pc_keyboard/",
    "drivers/input/keyboard/ps2_keyboard/",
    "drivers/input/mouse/",
    "drivers/input/mouse/ps2_mouse/",
    "drivers/nkuefi/",
    "drivers/rpi/",
    "drivers/sos/",
    "drivers/usbd/",
    # Fs
    "fs/fat/",
    # GPUs
    "drivers/gpu/armfb/",
    "drivers/gpu/vgag/",
    # Include
    "include/novusk/",
    # Kernel
    "init/",
    "kernel/kinfo/",
    "kernel/konfig/",
    "kernel/modules/",
    "kernel/notify/",
    "kernel/printk/",
    "kernel/setup/",
    # Libraries
    "lib/libbmu/",
    "lib/libc/",
    "lib/libcolor/",
    "lib/libost/",
    # MM
    "mm/io/",
    # Sound
    "sound/x86_64-sound/",
    # Kernel Modules
    "kernel/modules/ex1/",
    "kernel/modules/fscheck/",
    # Tools
    "tools/bootloader_image/",
]

[dependencies]
gpu = { path = "drivers/gpu/" }
kinfo = { path = "kernel/kinfo/" }
libc = { path = "lib/libc/" }
libcolor = { path = "lib/libcolor/" }
novuskinc = { path = "include/novusk/" }
printk = { path = "kernel/printk/" }
usbd = { path = "drivers/usbd/" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.18"
x86_64 = { path = "arch/x86_64/" }
x86_64-sound = { path = "sound/x86_64-sound" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = { path = "arch/aarch64/" }
libbmu = { path = "lib/libbmu/" }
rpi = { path = "drivers/rpi/" }

[target.'cfg(target_arch = "arm")'.dependencies]
libbmu = { path = "lib/libbmu/" }
arm = { path = "arch/arm/" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
libbmu = { path = "lib/libbmu/" }
riscv = { path = "arch/riscv" }

[target.'cfg(target_arch = "riscv32")'.dependencies]
libbmu = { path = "lib/libbmu/" }
riscv = { path = "arch/riscv" }

[target.'cfg(target_arch = "xtensa")'.dependencies]
xtensa = { path = "arch/xtensa/" }
xtensa-lx-rt = { version = "0.7.0", features = ["lx6"] }

[features]
bios_boot = ["x86_64/bios_boot"]
grub = ["x86_64/grub"]
hifive = ["riscv/hifive"]
rpi3 = ["aarch64/rpi3"]
stellaris_6965 = ["arm/stellaris_6965"]
uefi_boot = ["x86_64/uefi_boot"]
vga_0xa = ["x86_64/vga_0xa", "bootloader/vga_320x200"]
virt = ["aarch64/qemu_virt", "riscv/virt", "x86_64/virt"]
