[package]
name = "novusk"
version = "3.0.0-beta-arch-v3.2.1"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
path = "src/main.rs"
edition = "2018"

[lib]
name = "novusk"
path = "src/lib.rs"
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/aarch64/",
    "arch/arm/",
    "arch/riscv/",
    "arch/x86/",
    # Drivers
    "drivers/firmware/arm/nrfd/",
    "drivers/firmware/input/ps2/",
    "drivers/firmware/rpi/",
    "drivers/firmware/usbd/",
    "drivers/gpu/",
    "drivers/usb/",
    "drivers/nkuefi/",
    # GPUs
    # Kernel
    "kernel/kinfo/",
    "kernel/modules/",
    "kernel/printk/",
    # Libraries
    "lib/libbmu/",
    "lib/libc/",
    "lib/libcolor/",
    # MM
    "mm/io/",
    # Sound
    "sound/x86_64-sound/",
    # Kernel Modules
    "kernel/modules/ex1/",
    # Tools
    "tools/bootloader_image/",
]

[dependencies]
kinfo = { path = "kernel/kinfo/" }
libcolor = { path = "lib/libcolor/" }
printk = { path = "kernel/printk/" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.18"
x86 = { path = "arch/x86/" }
x86_64-sound = { path = "sound/x86_64-sound" }

[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path = "arch/x86/" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
libbmu = { path = "lib/libbmu/" }
aarch64 = { path = "arch/aarch64/" }

[target.'cfg(target_arch = "arm")'.dependencies]
libbmu = { path = "lib/libbmu/" }
arm = { path = "arch/arm/" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
libbmu = { path = "lib/libbmu/" }
riscv = { path = "arch/riscv" }

[target.'cfg(target_arch = "riscv32")'.dependencies]
libbmu = { path = "lib/libbmu/" }
riscv = { path = "arch/riscv" }

[features]
bios_boot = ["x86/bios_boot"]
uefi_boot = ["x86/uefi_boot"]
custom_keyboard = ["x86/custom_keyboard"]
grub = ["x86/grub"]
uk_keyboard = ["x86/uk_keyboard"]
us_keyboard = ["x86/us_keyboard"]
vga_0xa = ["x86/vga_0xa"]
nrf = ["arm/nrf"]
nrf52840 = ["arm/nrf52840"]
rpi3 = ["arm/rpi", "aarch64/rpi3"]
virt = ["aarch64/qemu_virt", "arm/virt", "riscv/virt", "x86/virt"]
hifive = ["riscv/hifive"]
