[package]
name = "novusk"
version = "2.1.3"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
path = "src/main.rs"
edition = "2018"

[lib]
name = "novusk"
path = "src/lib.rs"
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/x86/",
    # Drivers
    "drivers/gpu/",
    "drivers/nkuefi/",
    # GPUs
    # Kernel
    "kernel/kinfo/",
    "kernel/printk/",
    # Libraries
    "lib/libcolor/",
    # Sound
    "sound/x86_64-sound/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = { version = "0.9.12" }
x86 = { path = "arch/x86/" }

[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path = "arch/x86/" }

[dependencies]
libcolor = { path = "lib/libcolor/" }
register = { version = "1.0.2", optional = true }

[features]
default = []
bios_boot = ["register"]
bootloader_boot = ["register"]
custom_keyboard = ["register", "x86/custom_keyboard"]
grub_boot = ["register", "x86/grub"]
uk_keyboard = ["register", "x86/uk_keyboard"]
us_keyboard = ["register", "x86/us_keyboard"]
uefi_boot = ["register", "x86/uefi_boot"]
vga_buffer_320x200 = ["register", "bootloader/vga_320x200", "x86/vga_0xa"]
