[package]
name = "nrfd"
version = "0.1.0"
edition = "2018"
description = "Nrf board support"

[dependencies]
kinfo = { path = "../../../../kernel/kinfo/" }
libbmu = { path = "../../../../lib/libbmu/" }
novuskinc = { path = "../../../../include/novusk/" }
nrf52840-hal = "0.13.0"
nrf52840-pac = "0.10.1"
printk = { path = "../../../../kernel/printk/" }
