[package]
name = "nrfd"
version = "0.1.0"
edition = "2018"
description = "Nrf drivers"

[dependencies]
cortex-m = "0.7.3"
defmt = "0.2.3"
kinfo = { path = "../../../../kernel/kinfo" }
printk = { path = "../../../../kernel/printk/" }
nrf52840-hal = "0.12.2"
nrf52840-pac = "0.9.0"
nrf-usbd = "0.1.0"
usbd = { path = "../../../usbd/" }
usb-device = "0.2.8"
usbd-serial = "0.1.1"
