[package]
name = "riscv"
version = "0.1.0"
edition = "2018"
description = "RISCV32/64 kernel support"

[target.'cfg(target_arch = "riscv32")'.dependencies]
bl602-hal = { git = "https://github.com/sipeed/bl602-hal" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
io = { path = "../../mm/io/" }

[dependencies]
riscv-rt = "0.8.0"
risc-v = "0.0.0"

[features]
bl602 = []
virt = []
