[package]
name = "riscv"
version = "0.1.0"
edition = "2018"
description = "RISCV32/64 kernel support"

[target.'cfg(target_arch = "riscv32")'.dependencies]
hifive1 = { version = "0.10.0", features = ["board-hifive1"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
io = { path = "../../mm/io/" }

[dependencies]
kinfo = { path = "../../kernel/kinfo/" }
r0 = "1.0.0"
risc-v = "0.0.0"
riscv-rt = "0.8.0"

[features]
virt = []
hifive = []
