[package]
name = "nrfd"
version = "0.1.0"
edition = "2018"
description = "Nrf drivers"

[dependencies]
kinfo = { path = "../../../kernel/kinfo/" }
printk = { path = "../../../kernel/printk/" }
nrf52840-pac = "0.9.0"
nrf-usbd = "0.1.0"
usb-device = "0.2.8"
usbd-serial = "0.1.1"
