[package]
name = "nkuefi"
version = "0.1.0"
edition = "2018"
description = "Novusk Kernel UEFI boot and setup"

[dependencies]
uefi = "0.8.1"
uefi-services = { version = "0.5.1", features = ["no_panic_handler"] }
