[package]
name = "arm"
version = "0.1.0"
edition = "2018"
description = "arm family support for Novusk"

[target.'cfg(target_arch = "aarch64")'.dependencies]
rpi = { path = "../../drivers/rpi/" }

[target.'cfg(target_arch = "arm")'.dependencies]
nrfd = { path = "../../drivers/firmware/arm/nrfd/" }
nrf52840-hal = "0.12.2"
nrf52840-pac = "0.9.0"
cortex-m = "0.7.3"
cortex-m-rt = { version = "0.6.14" }
cortex-m-semihosting = "0.3.7"

[dependencies]
defmt = "0.2.3"
gpu = { path = "../../drivers/gpu/" }
kinfo = { path = "../../kernel/kinfo/" }
printk = { path = "../../kernel/printk/" }
usbd = { path = "../../drivers/usbd/" }
r0 = "1.0.0"

[features]
default = []
nrf = []
nrf52840 = ["nrf"]
rpi2 = []
rpi3 = []
rpi4 = []
virt = []
