[package]
name = "arm"
version = "0.1.0"
edition = "2018"
description = "arm32 support"

[dependencies]
alloc-cortex-m = "0.4.1"
cortex-m-rt = "0.7.0"
cortex-m-semihosting = "0.3.7"

[features]
stellaris_6965 = []
