[package]
name = "arm"
version = "0.1.0"
edition = "2018"
description = "arm family support for Novusk"

[target.'cfg(target_arch = "arm")'.dependencies]
nrfd = { path = "../../drivers/arm/nrfd/" }
nrf52840-hal = "0.12.2"
nrf52840-pac = "0.9.0"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = { version = "0.6.14" }
cortex-m-semihosting = "0.3.7"
defmt = "0.2.3"
kinfo = { path = "../../kernel/kinfo/" }
printk = { path = "../../kernel/printk/" }
usb = { path = "../../drivers/usb/" }
register = "1.0.2"
r0 = "1.0.0"

[features]
default = []
nrf = []
nrf52840 = ["nrf"]
rpi = []
