[package]
name = "x86_64"
version = "0.1.0"
edition = "2018"
description = "x86_64 support for Novusk"

[dependencies]
amd64_timer = "1.3.0"
bootloader = { version = "0.9.19", features = ["map_physical_memory"] }
gpu = { path = "../../drivers/gpu/" }
init = { path = "../../init/" }
kinfo = { path = "../../kernel/kinfo/" }
libcolor = { path = "../../lib/libcolor/" }
modules = { path = "../../kernel/modules/" }
nkuefi = { path = "../../drivers/nkuefi/" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
linked_list_allocator = "0.9.0"
novuskinc = { path = "../../include/novusk/" }
pic8259 = "0.10.1"
printk = { path = "../../kernel/printk/" }
ps2 = { path = "../../drivers/firmware/input/ps2/" }
volatile = "0.2.6"
raw-cpuid = "9.0.0"
setup = { path = "../../kernel/setup/" }
spin = { version = "0.9.2", features = ["spin_mutex"] }
usbd = { path = "../../drivers/usbd/" }
x86 = "0.41.0"
x86_64-sound = { path = "../../sound/x86_64-sound/" }
x86_64 = "0.14.4"

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]

[features]
bios_boot = []
custom_keyboard = ["ps2/custom_layout"]
grub = ["bios_boot"]
uefi_boot = []
uk_keyboard = ["ps2/uk_layout"]
us_keyboard = ["ps2/us_layout"]
vga_0xa = []
virt = []
