[package]
name = "pc_keyboard"
version = "0.1.0"
edition = "2018"
description = "PC keyboard support"

[dependencies]
keyboard = { path = "../../keyboard/" }
pc-keyboard = "0.5.1"
printk = { path = "../../../../kernel/printk/" }

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]

