[package]
name = "sos"
version = "0.1.0"
edition = "2018"
description = "Starts Novusk based OSes"

[dependencies]
blue = { path = "../blue/" }
libost = { path = "../../lib/libost" }
printk = { path = "../../kernel/printk/" }
