[package]
name = "rpi"
version = "0.1.0"
edition = "2018"
description = ""

[dependencies]
io = { path = "../../../mm/io/" }
libbmu = { path = "../../../lib/libbmu/" }
printk = { path = "../../../kernel/printk/" }
tock-registers = "0.7.0"
