[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]

[target.riscv32imac-unknown-none-elf]
runner = 'riscv32-unknown-elf-gdb'
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-melf32lriscv",
]
