[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 support for Novusk"

[dependencies]
arm = { path = "../arm/" }
bcm2837 = { git = "https://github.com/rcore-os/bcm2837/" }
r0 = "1.0.0"

[build-dependencies]
cc = "1.0.69"

[features]
default = ["rpi3"]
rpi3 = ["arm/rpi"]
qemu_virt = []
