[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 support for Novusk mostly a kernel for the RaspberryPi"

[dependencies]
arm = { path = "../arm/" }
bcm2837 = { git = "https://github.com/rcore-os/bcm2837/" }
io = { path = "../../mm/io/" }
r0 = "1.0.0"

[features]
default = ["rpi3"]
rpi3 = ["arm/rpi"]
qemu_virt = ["arm/virt"]
