[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 support for Novusk"

[dependencies]
# arm = { path = "../arm/" }
r0 = "1.0.0"

[features]
default = ["rpi3"]
rpi3 = []
qemu_virt = []
