[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 support for Novusk, mostly a kernel for the RaspberryPi"

[dependencies]
arm = { path = "../arm/" }
io = { path = "../../mm/io/" }
kinfo = { path = "../../kernel/kinfo/" }
libbmu = { path = "../../lib/libbmu/" }
modules = { path = "../../kernel/modules/" }
r0 = "1.0.0"
rpi = { path = "../../drivers/firmware/rpi/" }
tock-registers = "0.7.0"

[features]
default = ["rpi3"]
rpi3 = ["arm/rpi"]
qemu_virt = ["arm/virt"]
