[package]
name = "fscheck"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"


[dependencies]
fat = { path = "../../../fs/fat/" }
kinfo = { path = "../../kinfo/" }
konfig = { path = "../../konfig/", features = ["default_config"] }
novuskinc = { path = "../../../include/novusk/" }
